/// X-MACRO Database of country codes 
/// ISO 3166-1-alpha-2 | ISO 3166-1-alpha-3 | ISO 3166-1 numeric | UN Code | Short name | Long name |
/// Non-existent codes are set to 0. Non-existent strings are set to "".
/// Do not include this file explicitly in projects. Use implicit includes from headers \ code files to generate 
/// necessary pieces of information, if needed.
///
ES_COUNTRY_CODES_MAP_BEGIN
ES_COUNTRY_CODE_ENTRY(AF, AFG, 4, 4, "Afghanistan", "Islamic State of Afghanistan")
ES_COUNTRY_CODE_ENTRY(AL, ALB, 8, 8, "Albania", "Republic of Albania")
ES_COUNTRY_CODE_ENTRY(DZ, DZA, 12, 12, "Algeria", "Democratic and Popular Republic of Algeria")
ES_COUNTRY_CODE_ENTRY(AS, ASM, 16, 16, "American Samoa", "Territory of American Samoa")
ES_COUNTRY_CODE_ENTRY(AD, AND, 20, 20, "Andorra", "Principality of Andorra")
ES_COUNTRY_CODE_ENTRY(AO, AGO, 24, 24, "Angola", "Republic of Angola")
ES_COUNTRY_CODE_ENTRY(AI, AIA, 660, 660, "Anguilla", "")
ES_COUNTRY_CODE_ENTRY(AQ, ATA, 10, 10, "Antarctica", "")
ES_COUNTRY_CODE_ENTRY(AG, ATG, 28, 28, "Antigua and Barbuda", "Antigua and Barbuda")
ES_COUNTRY_CODE_ENTRY(AR, ARG, 32, 32, "Argentina", "Argentine Republic")
ES_COUNTRY_CODE_ENTRY(AM, ARM, 51, 51, "Armenia", "Republic of Armenia")
ES_COUNTRY_CODE_ENTRY(AW, ABW, 533, 533, "Aruba", "")
ES_COUNTRY_CODE_ENTRY(AU, AUS, 36, 36, "Australia", "Commonwealth of Australia")
ES_COUNTRY_CODE_ENTRY(AT, AUT, 40, 40, "Austria", "Republic of Austria")
ES_COUNTRY_CODE_ENTRY(AZ, AZE, 31, 31, "Azerbaijan", "Azerbaijani Republic")
ES_COUNTRY_CODE_ENTRY(BS, BHS, 44, 44, "Bahamas, The", "The Commonwealth of The Bahamas")
ES_COUNTRY_CODE_ENTRY(BH, BHR, 48, 48, "Bahrain", "State of Bahrain")
ES_COUNTRY_CODE_ENTRY(BD, BGD, 50, 50, "Bangladesh", "People's Republic of Bangladesh")
ES_COUNTRY_CODE_ENTRY(BB, BRB, 52, 52, "Barbados", "")
ES_COUNTRY_CODE_ENTRY(BY, BLR, 112, 112, "Belarus", "Republic of Belarus")
ES_COUNTRY_CODE_ENTRY(BE, BEL, 56, 56, "Belgium", "Kingdom of Belgium")
ES_COUNTRY_CODE_ENTRY(BZ, BLZ, 84, 84, "Belize", "")
ES_COUNTRY_CODE_ENTRY(BJ, BEN, 204, 204, "Benin", "Republic of Benin")
ES_COUNTRY_CODE_ENTRY(BM, BMU, 60, 60, "Bermuda", "")
ES_COUNTRY_CODE_ENTRY(BT, BTN, 64, 64, "Bhutan", "Kingdom of Bhutan")
ES_COUNTRY_CODE_ENTRY(BO, BOL, 68, 68, "Bolivia", "Republic of Bolivia")
ES_COUNTRY_CODE_ENTRY(BA, BIH, 70, 70, "Bosnia and Herzegovina", "Republic of Bosnia and Herzegovina")
ES_COUNTRY_CODE_ENTRY(BW, BWA, 72, 72, "Botswana", "Republic of Botswana")
ES_COUNTRY_CODE_ENTRY(BV, BVT, 74, 0, "Bouvet Island", "")
ES_COUNTRY_CODE_ENTRY(BR, BRA, 76, 76, "Brazil", "Federative Republic of Brazil")
ES_COUNTRY_CODE_ENTRY(IO, IOT, 86, 0, "British Indian Ocean Territory", "British Indian Ocean Territory")
ES_COUNTRY_CODE_ENTRY(BN, BRN, 96, 96, "Brunei", "Negara Brunei Darussalam")
ES_COUNTRY_CODE_ENTRY(BG, BGR, 100, 100, "Bulgaria", "Republic of Bulgaria")
ES_COUNTRY_CODE_ENTRY(BF, BFA, 854, 854, "Burkina Faso", "")
ES_COUNTRY_CODE_ENTRY(BI, BDI, 108, 108, "Burundi", "Republic of Burundi")
ES_COUNTRY_CODE_ENTRY(CI, CIV, 384, 384, "Côte d'Ivoire", "Republic of Côte d'Ivoire")
ES_COUNTRY_CODE_ENTRY(KH, KHM, 116, 116, "Cambodia", "Kingdom of Cambodia")
ES_COUNTRY_CODE_ENTRY(CM, CMR, 120, 120, "Cameroon", "Republic of Cameroon")
ES_COUNTRY_CODE_ENTRY(CA, CAN, 124, 124, "Canada", "")
ES_COUNTRY_CODE_ENTRY(CV, CPV, 132, 132, "Cape Verde", "Republic of Cape Verde")
ES_COUNTRY_CODE_ENTRY(KY, CYM, 136, 136, "Cayman Islands", "")
ES_COUNTRY_CODE_ENTRY(CF, CAF, 140, 140, "Central African Republic", "Central African Republic")
ES_COUNTRY_CODE_ENTRY(TD, TCD, 148, 148, "Chad", "Republic of Chad")
ES_COUNTRY_CODE_ENTRY(CL, CHL, 152, 152, "Chile", "Republic of Chile")
ES_COUNTRY_CODE_ENTRY(CN, CHN, 156, 156, "China", "People's Republic of China")
ES_COUNTRY_CODE_ENTRY(CX, CXR, 162, 0, "Christmas Island", "Territory of Christmas Island")
ES_COUNTRY_CODE_ENTRY(CC, CCK, 166, 0, "Cocos (Keeling Islands"), "Territory of Cocos (Keeling Islands"))
ES_COUNTRY_CODE_ENTRY(CO, COL, 170, 170, "Colombia", "Republic of Colombia")
ES_COUNTRY_CODE_ENTRY(KM, COM, 174, 174, "Comoros", "Federal Islamic Republic of the Comoros")
ES_COUNTRY_CODE_ENTRY(CG, COG, 178, 178, "Congo", "Republic of the Congo")
ES_COUNTRY_CODE_ENTRY(CD, COD, 180, 180, "Congo (DRC"), "Democratic Republic of the Congo")
ES_COUNTRY_CODE_ENTRY(CK, COK, 184, 184, "Cook Islands", "")
ES_COUNTRY_CODE_ENTRY(CR, CRI, 188, 188, "Costa Rica", "Republic of Costa Rica")
ES_COUNTRY_CODE_ENTRY(HR, HRV, 191, 191, "Croatia", "Republic of Croatia")
ES_COUNTRY_CODE_ENTRY(CU, CUB, 192, 192, "Cuba", "Republic of Cuba")
ES_COUNTRY_CODE_ENTRY(CY, CYP, 196, 196, "Cyprus", "Republic of Cyprus")
ES_COUNTRY_CODE_ENTRY(CZ, CZE, 203, 203, "Czech Republic", "Czech Republic")
ES_COUNTRY_CODE_ENTRY(DK, DNK, 208, 208, "Denmark", "Kingdom of Denmark")
ES_COUNTRY_CODE_ENTRY(DJ, DJI, 262, 262, "Djibouti", "Republic of Djibouti")
ES_COUNTRY_CODE_ENTRY(DM, DMA, 212, 212, "Dominica", "Commonwealth of Dominica")
ES_COUNTRY_CODE_ENTRY(DO, DOM, 214, 214, "Dominican Republic", "Dominican Republic")
ES_COUNTRY_CODE_ENTRY(TP, TMP, 626, 626, "East Timor", "")
ES_COUNTRY_CODE_ENTRY(EC, ECU, 218, 218, "Ecuador", "Republic of Ecuador")
ES_COUNTRY_CODE_ENTRY(EG, EGY, 818, 818, "Egypt", "Arab Republic of Egypt")
ES_COUNTRY_CODE_ENTRY(SV, SLV, 222, 222, "El Salvador", "Republic of El Salvador")
ES_COUNTRY_CODE_ENTRY(GQ, GNQ, 226, 226, "Equatorial Guinea", "Republic of Equatorial Guinea")
ES_COUNTRY_CODE_ENTRY(ER, ERI, 232, 232, "Eritrea", "State of Eritrea")
ES_COUNTRY_CODE_ENTRY(EE, EST, 233, 233, "Estonia", "Republic of Estonia")
ES_COUNTRY_CODE_ENTRY(ET, ETH, 231, 231, "Ethiopia", "Federal Democratic Republic of Ethiopia")
ES_COUNTRY_CODE_ENTRY(FK, FLK, 238, 238, "Falkland Islands (Islas Malvinas"), "Falkland Islands (Islas Malvinas"))
ES_COUNTRY_CODE_ENTRY(FO, FRO, 234, 234, "Faroe Islands", "")
ES_COUNTRY_CODE_ENTRY(FJ, FJI, 242, 242, "Fiji Islands", "Republic of the Fiji Islands")
ES_COUNTRY_CODE_ENTRY(FI, FIN, 246, 246, "Finland", "Republic of Finland")
ES_COUNTRY_CODE_ENTRY(FR, FRA, 250, 250, "France", "French Republic")
ES_COUNTRY_CODE_ENTRY(FX, FXX, 249, 0, "France, Metropolitan", "")
ES_COUNTRY_CODE_ENTRY(GF, GUF, 254, 254, "French Guiana", "Department of Guiana")
ES_COUNTRY_CODE_ENTRY(PF, PYF, 258, 258, "French Polynesia", "Territory of French Polynesia")
ES_COUNTRY_CODE_ENTRY(TF, ATF, 260, 0, "French Southern and Antarctic Lands", "Territory of the French Southern and Antarctic Lands")
ES_COUNTRY_CODE_ENTRY(GA, GAB, 266, 266, "Gabon", "Gabonese Republic")
ES_COUNTRY_CODE_ENTRY(GM, GMB, 270, 270, "Gambia, The", "Republic of The Gambia")
ES_COUNTRY_CODE_ENTRY(GE, GEO, 268, 268, "Georgia", "Republic of Georgia")
ES_COUNTRY_CODE_ENTRY(DE, DEU, 276, 276, "Germany", "Federal Republic of Germany")
ES_COUNTRY_CODE_ENTRY(GH, GHA, 288, 288, "Ghana", "Republic of Ghana")
ES_COUNTRY_CODE_ENTRY(GI, GIB, 292, 292, "Gibraltar", "")
ES_COUNTRY_CODE_ENTRY(GR, GRC, 300, 300, "Greece", "Hellenic Republic")
ES_COUNTRY_CODE_ENTRY(GL, GRL, 304, 304, "Greenland", "")
ES_COUNTRY_CODE_ENTRY(GD, GRD, 308, 308, "Grenada", "")
ES_COUNTRY_CODE_ENTRY(GP, GLP, 312, 312, "Guadeloupe", "Department of Guadeloupe")
ES_COUNTRY_CODE_ENTRY(GU, GUM, 316, 316, "Guam", "Territory of Guam")
ES_COUNTRY_CODE_ENTRY(GT, GTM, 320, 320, "Guatemala", "Republic of Guatemala")
ES_COUNTRY_CODE_ENTRY(GN, GIN, 324, 324, "Guinea", "Republic of Guinea")
ES_COUNTRY_CODE_ENTRY(GW, GNB, 624, 624, "Guinea-Bissau", "Republic of Guinea-Bissau")
ES_COUNTRY_CODE_ENTRY(GY, GUY, 328, 328, "Guyana", "Cooperative Republic of Guyana")
ES_COUNTRY_CODE_ENTRY(HT, HTI, 332, 332, "Haiti", "Republic of Haiti")
ES_COUNTRY_CODE_ENTRY(HM, HMD, 334, 0, "Heard Island and McDonald Islands", "Territory of Heard Island and McDonald Islands")
ES_COUNTRY_CODE_ENTRY(HN, HND, 340, 340, "Honduras", "Republic of Honduras")
ES_COUNTRY_CODE_ENTRY(HK, HKG, 344, 344, "Hong Kong SAR", "Hong Kong Special Administrative Region")
ES_COUNTRY_CODE_ENTRY(HU, HUN, 348, 348, "Hungary", "Republic of Hungary")
ES_COUNTRY_CODE_ENTRY(IS, ISL, 352, 352, "Iceland", "Republic of Iceland")
ES_COUNTRY_CODE_ENTRY(IN, IND, 356, 356, "India", "Republic of India")
ES_COUNTRY_CODE_ENTRY(ID, IDN, 360, 360, "Indonesia", "Republic of Indonesia")
ES_COUNTRY_CODE_ENTRY(IR, IRN, 364, 364, "Iran", "Islamic Republic of Iran")
ES_COUNTRY_CODE_ENTRY(IQ, IRQ, 368, 368, "Iraq", "Republic of Iraq")
ES_COUNTRY_CODE_ENTRY(IE, IRL, 372, 372, "Ireland", "Republic of Ireland")
ES_COUNTRY_CODE_ENTRY(IL, ISR, 376, 376, "Israel", "State of Israel")
ES_COUNTRY_CODE_ENTRY(IT, ITA, 380, 380, "Italy", "Italian Republic")
ES_COUNTRY_CODE_ENTRY(JM, JAM, 388, 388, "Jamaica", "")
ES_COUNTRY_CODE_ENTRY(JP, JPN, 392, 392, "Japan", "")
ES_COUNTRY_CODE_ENTRY(JO, JOR, 400, 400, "Jordan", "Hashemite Kingdom of Jordan")
ES_COUNTRY_CODE_ENTRY(KZ, KAZ, 398, 398, "Kazakhstan", "Republic of Kazakhstan")
ES_COUNTRY_CODE_ENTRY(KE, KEN, 404, 404, "Kenya", "Republic of Kenya")
ES_COUNTRY_CODE_ENTRY(KI, KIR, 296, 296, "Kiribati", "Republic of Kiribati")
ES_COUNTRY_CODE_ENTRY(KR, KOR, 410, 410, "Korea", "Republic of Korea")
ES_COUNTRY_CODE_ENTRY(KW, KWT, 414, 414, "Kuwait", "State of Kuwait")
ES_COUNTRY_CODE_ENTRY(KG, KGZ, 417, 417, "Kyrgyzstan", "Kyrgyz Republic")
ES_COUNTRY_CODE_ENTRY(LA, LAO, 418, 418, "Laos", "Lao People's Democratic Republic")
ES_COUNTRY_CODE_ENTRY(LV, LVA, 428, 428, "Latvia", "Republic of Latvia")
ES_COUNTRY_CODE_ENTRY(LB, LBN, 422, 422, "Lebanon", "Republic of Lebanon")
ES_COUNTRY_CODE_ENTRY(LS, LSO, 426, 426, "Lesotho", "Kingdom of Lesotho")
ES_COUNTRY_CODE_ENTRY(LR, LBR, 430, 430, "Liberia", "Republic of Liberia")
ES_COUNTRY_CODE_ENTRY(LY, LBY, 434, 434, "Libya", "Socialist People's Libyan Arab Jamahiriya")
ES_COUNTRY_CODE_ENTRY(LI, LIE, 438, 438, "Liechtenstein", "Principality of Liechtenstein")
ES_COUNTRY_CODE_ENTRY(LT, LTU, 440, 440, "Lithuania", "Republic of Lithuania")
ES_COUNTRY_CODE_ENTRY(LU, LUX, 442, 442, "Luxembourg", "Grand Duchy of Luxembourg")
ES_COUNTRY_CODE_ENTRY(MO, MAC, 446, 446, "Macau SAR", "Macau Special Administrative Region")
ES_COUNTRY_CODE_ENTRY(MK, MKD, 807, 807, "Macedonia, Former Yugoslav Republic of", "The Former Yugoslav Republic of Macedonia")
ES_COUNTRY_CODE_ENTRY(MG, MDG, 450, 450, "Madagascar", "Republic of Madagascar")
ES_COUNTRY_CODE_ENTRY(MW, MWI, 454, 454, "Malawi", "Republic of Malawi")
ES_COUNTRY_CODE_ENTRY(MY, MYS, 458, 458, "Malaysia", "Federation of Malaysia")
ES_COUNTRY_CODE_ENTRY(MV, MDV, 462, 462, "Maldives", "Republic of Maldives")
ES_COUNTRY_CODE_ENTRY(ML, MLI, 466, 466, "Mali", "Republic of Mali")
ES_COUNTRY_CODE_ENTRY(MT, MLT, 470, 470, "Malta", "Republic of Malta")
ES_COUNTRY_CODE_ENTRY(MH, MHL, 584, 584, "Marshall Islands", "Republic of the Marshall Islands")
ES_COUNTRY_CODE_ENTRY(MQ, MTQ, 474, 474, "Martinique", "Department of Martinique")
ES_COUNTRY_CODE_ENTRY(MR, MRT, 478, 478, "Mauritania", "Islamic Republic of Mauritania")
ES_COUNTRY_CODE_ENTRY(MU, MUS, 480, 480, "Mauritius", "Republic of Mauritius")
ES_COUNTRY_CODE_ENTRY(YT, MYT, 175, 0, "Mayotte", "Territorial Collectivity of Mayotte")
ES_COUNTRY_CODE_ENTRY(MX, MEX, 484, 484, "Mexico", "United Mexican States")
ES_COUNTRY_CODE_ENTRY(FM, FSM, 583, 583, "Micronesia", "Federated States of Micronesia")
ES_COUNTRY_CODE_ENTRY(MD, MDA, 498, 498, "Moldova", "Republic of Moldova")
ES_COUNTRY_CODE_ENTRY(MC, MCO, 492, 492, "Monaco", "Principality of Monaco")
ES_COUNTRY_CODE_ENTRY(MN, MNG, 496, 496, "Mongolia", "")
ES_COUNTRY_CODE_ENTRY(MS, MSR, 500, 500, "Montserrat", "")
ES_COUNTRY_CODE_ENTRY(MA, MAR, 504, 504, "Morocco", "Kingdom of Morocco")
ES_COUNTRY_CODE_ENTRY(MZ, MOZ, 508, 508, "Mozambique", "Republic of Mozambique")
ES_COUNTRY_CODE_ENTRY(MM, MMR, 104, 104, "Myanmar", "Union of Myanmar")
ES_COUNTRY_CODE_ENTRY(NA, NAM, 516, 516, "Namibia", "Republic of Namibia")
ES_COUNTRY_CODE_ENTRY(NR, NRU, 520, 520, "Nauru", "Republic of Nauru")
ES_COUNTRY_CODE_ENTRY(NP, NPL, 524, 524, "Nepal", "Kingdom of Nepal")
ES_COUNTRY_CODE_ENTRY(AN, ANT, 530, 530, "Netherlands Antilles", "")
ES_COUNTRY_CODE_ENTRY(NL, NLD, 528, 528, "Netherlands, The", "Kingdom of the Netherlands")
ES_COUNTRY_CODE_ENTRY(NC, NCL, 540, 540, "New Caledonia", "Territory of New Caledonia and Dependencies")
ES_COUNTRY_CODE_ENTRY(NZ, NZL, 554, 554, "New Zealand", "")
ES_COUNTRY_CODE_ENTRY(NI, NIC, 558, 558, "Nicaragua", "Republic of Nicaragua")
ES_COUNTRY_CODE_ENTRY(NE, NER, 562, 562, "Niger", "Republic of Niger")
ES_COUNTRY_CODE_ENTRY(NG, NGA, 566, 566, "Nigeria", "Federal Republic of Nigeria")
ES_COUNTRY_CODE_ENTRY(NU, NIU, 570, 570, "Niue", "")
ES_COUNTRY_CODE_ENTRY(NF, NFK, 574, 574, "Norfolk Island", "Territory of Norfolk Island")
ES_COUNTRY_CODE_ENTRY(KP, PRK, 408, 408, "North Korea", "Democratic People's Republic of Korea")
ES_COUNTRY_CODE_ENTRY(MP, MNP, 580, 580, "Northern Mariana Islands", "Commonwealth of the Northern Mariana Islands")
ES_COUNTRY_CODE_ENTRY(NO, NOR, 578, 578, "Norway", "Kingdom of Norway")
ES_COUNTRY_CODE_ENTRY(OM, OMN, 512, 512, "Oman", "Sultanate of Oman")
ES_COUNTRY_CODE_ENTRY(PK, PAK, 586, 586, "Pakistan", "Islamic Republic of Pakistan")
ES_COUNTRY_CODE_ENTRY(PW, PLW, 585, 585, "Palau", "Republic of Palau")
ES_COUNTRY_CODE_ENTRY(PA, PAN, 591, 591, "Panama", "Republic of Panama")
ES_COUNTRY_CODE_ENTRY(PG, PNG, 598, 598, "Papua New Guinea", "Independent State of Papua New Guinea")
ES_COUNTRY_CODE_ENTRY(PY, PRY, 600, 600, "Paraguay", "Republic of Paraguay")
ES_COUNTRY_CODE_ENTRY(PE, PER, 604, 604, "Peru", "Republic of Peru")
ES_COUNTRY_CODE_ENTRY(PH, PHL, 608, 608, "Philippines", "Republic of the Philippines")
ES_COUNTRY_CODE_ENTRY(PN, PCN, 612, 612, "Pitcairn Islands", "Pitcairn, Henderson, Ducie, and Oeno Islands")
ES_COUNTRY_CODE_ENTRY(PL, POL, 616, 616, "Poland", "Republic of Poland")
ES_COUNTRY_CODE_ENTRY(PT, PRT, 620, 620, "Portugal", "Portuguese Republic")
ES_COUNTRY_CODE_ENTRY(PR, PRI, 630, 630, "Puerto Rico", "Commonwealth of Puerto Rico")
ES_COUNTRY_CODE_ENTRY(QA, QAT, 634, 634, "Qatar", "State of Qatar")
ES_COUNTRY_CODE_ENTRY(RE, REU, 638, 638, "Reunion", "Department of Reunion")
ES_COUNTRY_CODE_ENTRY(RO, ROM, 642, 642, "Romania", "")
ES_COUNTRY_CODE_ENTRY(RU, RUS, 643, 643, "Russia", "Russian Federation")
ES_COUNTRY_CODE_ENTRY(RW, RWA, 646, 646, "Rwanda", "Rwandese Republic")
ES_COUNTRY_CODE_ENTRY(ST, STP, 678, 678, "São Tomé and Príncipe", "Democratic Republic of São Tomé and Príncipe")
ES_COUNTRY_CODE_ENTRY(WS, WSM, 882, 882, "Samoa", "Independent State of Samoa")
ES_COUNTRY_CODE_ENTRY(SM, SMR, 674, 674, "San Marino", "Republic of San Marino")
ES_COUNTRY_CODE_ENTRY(SA, SAU, 682, 682, "Saudi Arabia", "Kingdom of Saudi Arabia")
ES_COUNTRY_CODE_ENTRY(SN, SEN, 686, 686, "Senegal", "Republic of Senegal")
ES_COUNTRY_CODE_ENTRY(SC, SYC, 690, 690, "Seychelles", "Republic of Seychelles")
ES_COUNTRY_CODE_ENTRY(SL, SLE, 694, 694, "Sierra Leone", "Republic of Sierra Leone")
ES_COUNTRY_CODE_ENTRY(SG, SGP, 702, 702, "Singapore", "Republic of Singapore")
ES_COUNTRY_CODE_ENTRY(SK, SVK, 703, 703, "Slovakia", "Slovak Republic")
ES_COUNTRY_CODE_ENTRY(SI, SVN, 705, 705, "Slovenia", "Republic of Slovenia")
ES_COUNTRY_CODE_ENTRY(SB, SLB, 90, 90, "Solomon Islands", "")
ES_COUNTRY_CODE_ENTRY(SO, SOM, 706, 706, "Somalia", "Somali Democratic Republic")
ES_COUNTRY_CODE_ENTRY(ZA, ZAF, 710, 710, "South Africa", "Republic of South Africa")
ES_COUNTRY_CODE_ENTRY(GS, SGS, 239, 0, "South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands")
ES_COUNTRY_CODE_ENTRY(ES, ESP, 724, 724, "Spain", "Kingdom of Spain")
ES_COUNTRY_CODE_ENTRY(LK, LKA, 144, 144, "Sri Lanka", "Democratic Socialist Republic of Sri Lanka")
ES_COUNTRY_CODE_ENTRY(SH, SHN, 654, 654, "St. Helena", "Saint Helena")
ES_COUNTRY_CODE_ENTRY(KN, KNA, 659, 659, "St. Kitts and Nevis", "Federation of Saint Kitts and Nevis")
ES_COUNTRY_CODE_ENTRY(LC, LCA, 662, 662, "St. Lucia", "Saint Lucia")
ES_COUNTRY_CODE_ENTRY(PM, SPM, 666, 666, "St. Pierre and Miquelon", "Territorial Collectivity of Saint Pierre and Miquelon")
ES_COUNTRY_CODE_ENTRY(VC, VCT, 670, 670, "St. Vincent and the Grenadines", "Saint Vincent and the Grenadines")
ES_COUNTRY_CODE_ENTRY(SD, SDN, 736, 736, "Sudan", "Republic of the Sudan")
ES_COUNTRY_CODE_ENTRY(SR, SUR, 740, 740, "Suriname", "Republic of Suriname")
ES_COUNTRY_CODE_ENTRY(SJ, SJM, 744, 744, "Svalbard and Jan Mayen", "")
ES_COUNTRY_CODE_ENTRY(SZ, SWZ, 748, 748, "Swaziland", "Kingdom of Swaziland")
ES_COUNTRY_CODE_ENTRY(SE, SWE, 752, 752, "Sweden", "Kingdom of Sweden")
ES_COUNTRY_CODE_ENTRY(CH, CHE, 756, 756, "Switzerland", "Swiss Confederation")
ES_COUNTRY_CODE_ENTRY(SY, SYR, 760, 760, "Syria", "Syrian Arab Republic")
ES_COUNTRY_CODE_ENTRY(TW, TWN, 158, 158, "Taiwan", "")
ES_COUNTRY_CODE_ENTRY(TJ, TJK, 762, 762, "Tajikistan", "Republic of Tajikistan")
ES_COUNTRY_CODE_ENTRY(TZ, TZA, 834, 834, "Tanzania", "United Republic of Tanzania")
ES_COUNTRY_CODE_ENTRY(TH, THA, 764, 764, "Thailand", "Kingdom of Thailand")
ES_COUNTRY_CODE_ENTRY(TG, TGO, 768, 768, "Togo", "Togolese Republic")
ES_COUNTRY_CODE_ENTRY(TK, TKL, 772, 772, "Tokelau", "")
ES_COUNTRY_CODE_ENTRY(TO, TON, 776, 776, "Tonga", "Kingdom of Tonga")
ES_COUNTRY_CODE_ENTRY(TT, TTO, 780, 780, "Trinidad and Tobago", "Republic of Trinidad and Tobago")
ES_COUNTRY_CODE_ENTRY(TN, TUN, 788, 788, "Tunisia", "Republic of Tunisia")
ES_COUNTRY_CODE_ENTRY(TR, TUR, 792, 792, "Turkey", "Republic of Turkey")
ES_COUNTRY_CODE_ENTRY(TM, TKM, 795, 795, "Turkmenistan", "Republic of Turkmenistan")
ES_COUNTRY_CODE_ENTRY(TC, TCA, 796, 796, "Turks and Caicos Islands", "")
ES_COUNTRY_CODE_ENTRY(TV, TUV, 798, 798, "Tuvalu", "")
ES_COUNTRY_CODE_ENTRY(UM, UMI, 581, 581, "U.S. Minor Outlying Islands", "United States Minor Outlying Islands")
ES_COUNTRY_CODE_ENTRY(UG, UGA, 800, 800, "Uganda", "Republic of Uganda")
ES_COUNTRY_CODE_ENTRY(UA, UKR, 804, 804, "Ukraine", "")
ES_COUNTRY_CODE_ENTRY(AE, ARE, 784, 784, "United Arab Emirates", "")
ES_COUNTRY_CODE_ENTRY(GB, GBR, 826, 826, "United Kingdom", "United Kingdom of Great Britain and Northern Ireland")
ES_COUNTRY_CODE_ENTRY(US, USA, 840, 840, "United States", "United States of America")
ES_COUNTRY_CODE_ENTRY(UY, URY, 858, 858, "Uruguay", "Oriental Republic of Uruguay")
ES_COUNTRY_CODE_ENTRY(UZ, UZB, 860, 860, "Uzbekistan", "Republic of Uzbekistan")
ES_COUNTRY_CODE_ENTRY(VU, VUT, 548, 548, "Vanuatu", "Republic of Vanuatu")
ES_COUNTRY_CODE_ENTRY(VA, VAT, 336, 336, "Vatican City", "State of Vatican City")
ES_COUNTRY_CODE_ENTRY(VE, VEN, 862, 862, "Venezuela", "Bolivarian Republic of Venezuela")
ES_COUNTRY_CODE_ENTRY(VN, VNM, 704, 704, "Viet Nam", "Socialist Republic of Vietnam")
ES_COUNTRY_CODE_ENTRY(VI, VIR, 850, 850, "Virgin Islands", "Virgin Islands of the United States")
ES_COUNTRY_CODE_ENTRY(VG, VGB, 92, 92, "Virgin Islands, British", "")
ES_COUNTRY_CODE_ENTRY(WF, WLF, 876, 876, "Wallis and Futuna", "Territory of the Wallis and Futuna Islands")
ES_COUNTRY_CODE_ENTRY(YE, YEM, 887, 887, "Yemen", "Republic of Yemen")
ES_COUNTRY_CODE_ENTRY(YU, YUG, 891, 891, "Yugoslavia", "Federal Republic of Yugoslavia")
ES_COUNTRY_CODE_ENTRY(ZM, ZMB, 894, 894, "Zambia", "Republic of Zambia")
ES_COUNTRY_CODE_ENTRY(ZW, ZWE, 716, 716, "Zimbabwe", "Republic of Zimbabwe")
ES_COUNTRY_CODES_MAP_END

#undef ES_COUNTRY_CODES_MAP_BEGIN
#undef ES_COUNTRY_CODE_ENTRY
#undef ES_COUNTRY_CODES_MAP_END
