// ECO-E devices description strings
ESE_I18N_STRING_ENTRY(en,   istrBOI1_DCR_SHORT,       "BOI-01")
ESE_I18N_STRING_ENTRY(en,   istrBOI1_DCR_LONG,        "Measurement Control Hub BOI-01")
ESE_I18N_STRING_ENTRY(en,   istrECOL1_DCR_SHORT,      "FG-01")
ESE_I18N_STRING_ENTRY(en,   istrECOL1_DCR_LONG,       "Lux, Chroma, Flicker meter, FG-01")
ESE_I18N_STRING_ENTRY(en,   istrBOI2L_DCR_SHORT,      "BOI-02F")
ESE_I18N_STRING_ENTRY(en,   istrBOI2L_DCR_LONG,       "Measurement Control Hub BOI-02F")
ESE_I18N_STRING_ENTRY(en,   istrBOI2T_DCR_SHORT,      "BOI-02T")
ESE_I18N_STRING_ENTRY(en,   istrBOI2T_DCR_LONG,       "Measurement Control Hub BOI-02T")
ESE_I18N_STRING_ENTRY(en,   istrET1_DCR_SHORT,        "ET-01")
ESE_I18N_STRING_ENTRY(en,   istrET1_DCR_LONG,         "Metheo parameters meter EcoTherma-01")
ESE_I18N_STRING_ENTRY(en,   istrEGEM1_DCR_SHORT,      "GEO-01")
ESE_I18N_STRING_ENTRY(en,   istrEGEM1_DCR_LONG,       "Geo-magnetic field meter GEO-01")
ESE_I18N_STRING_ENTRY(en,   istrRAD1_DCR_SHORT,       "RAD-01")
ESE_I18N_STRING_ENTRY(en,   istrRAD1_DCR_LONG,        "Radon radiometer RAD-01")
ESE_I18N_STRING_ENTRY(en,   istrIRA1_DCR_SHORT,       "IRA-01")
ESE_I18N_STRING_ENTRY(en,   istrIRA1_DCR_LONG,        "Infrared radioation meter IRA-01")
ESE_I18N_STRING_ENTRY(en,   istrLD1V_DCR_SHORT,       "LD-01-V")
ESE_I18N_STRING_ENTRY(en,   istrLD1V_DCR_LONG,        "LASER radiation dosimeter LD-01-V")
ESE_I18N_STRING_ENTRY(en,   istrOAA_DCR_SHORT,        "OMC")
ESE_I18N_STRING_ENTRY(en,   istrOAA_DCR_LONG,         "Octava meters converter")
ESE_I18N_STRING_ENTRY(en,   istrEL3C_DCR_SHORT,       "eL-03-C")
ESE_I18N_STRING_ENTRY(en,   istrEL3C_DCR_LONG,        "Lux, Chroma, Flicker, Colour meter, eLight-03-C")
ESE_I18N_STRING_ENTRY(en,   istrECLG1_DCR_SHORT,      "eCLg-01")
ESE_I18N_STRING_ENTRY(en,   istrECLG1_DCR_LONG,       "eCoLogger-01")
ESE_I18N_STRING_ENTRY(en,   istrLUPINX_DCR_SHORT,     "Lupin-X")
ESE_I18N_STRING_ENTRY(en,   istrLUPINX_DCR_LONG,      "Lux, Chroma, Flicker meter, Lupin-X")
// Octava devices description strings
ESE_I18N_STRING_ENTRY(en,   istrP380E_DCR_SHORT,      "P3-80E")
ESE_I18N_STRING_ENTRY(en,   istrP380E_DCR_LONG,       "Electrostatic field meter P3-80E")
ESE_I18N_STRING_ENTRY(en,   istrP3811_DCR_SHORT,      "P3-81-1")
ESE_I18N_STRING_ENTRY(en,   istrP3811_DCR_LONG,       "Magnetic induction meter P3-81-1 mTl")
ESE_I18N_STRING_ENTRY(en,   istrP3812_DCR_SHORT,      "P3-81-2")
ESE_I18N_STRING_ENTRY(en,   istrP3812_DCR_LONG,       "Magnetic induction meter P3-81-2 uTl")	
// Tenzor devices description strings
ESE_I18N_STRING_ENTRY(en,   istrTECOL1_DCR_SHORT,     "GF-01")
ESE_I18N_STRING_ENTRY(en,   istrTECOL1_DCR_LONG,      "Lux, Chroma, Flicker meter, GF-01")
ESE_I18N_STRING_ENTRY(en,   istrTBOI1_DCR_SHORT,      "BOI-01-T")
ESE_I18N_STRING_ENTRY(en,   istrTBOI1_DCR_LONG,       "Measurement Control Hub BOI-01-T")
ESE_I18N_STRING_ENTRY(en,   istrTIRA1_DCR_SHORT,      "IRA-01-T")
ESE_I18N_STRING_ENTRY(en,   istrTIRA1_DCR_LONG,       "Infrared radioation meter IRA-01-T")
// Quarta-Rad appliances|hubs description strings
ESE_I18N_STRING_ENTRY(en,   istrRADEX1_DCR_SHORT,     "RADEX1")
ESE_I18N_STRING_ENTRY(en,   istrRADEX1_DCR_LONG,      "Radex One Mini Dosimeter")
ESE_I18N_STRING_ENTRY(en,   istrMKC1100_DCR_SHORT,    "MKC1100")
ESE_I18N_STRING_ENTRY(en,   istrMKC1100_DCR_LONG,     "MKC1100 Dosimeter")
ESE_I18N_STRING_ENTRY(en,   istrMR107_DCR_SHORT,      "MR107")
ESE_I18N_STRING_ENTRY(en,   istrMR107_DCR_LONG,       "MR107 Radon Radiometer")
ESE_I18N_STRING_ENTRY(en,   istrAQ_DCR_SHORT,         "AQ")
ESE_I18N_STRING_ENTRY(en,   istrAQ_DCR_LONG,          "Air Quality Monitor")
