// ECO-E devices description strings
ESE_I18N_STRING_ENTRY(ru,   istrBOI1_DCR_SHORT,       "БОИ-01")
ESE_I18N_STRING_ENTRY(ru,   istrBOI1_DCR_LONG,        "Блок отображения информации БОИ-01")
ESE_I18N_STRING_ENTRY(ru,   istrECOL1_DCR_SHORT,      "ФГ-01")
ESE_I18N_STRING_ENTRY(ru,   istrECOL1_DCR_LONG,       "Фотоголовка ФГ-01")
ESE_I18N_STRING_ENTRY(ru,   istrBOI2L_DCR_SHORT,      "БОИ-02Ф")
ESE_I18N_STRING_ENTRY(ru,   istrBOI2L_DCR_LONG,       "Блок отображения информации БОИ-02Ф")
ESE_I18N_STRING_ENTRY(ru,   istrBOI2T_DCR_SHORT,      "БОИ-02Т")
ESE_I18N_STRING_ENTRY(ru,   istrBOI2T_DCR_LONG,       "Блок отображения информации БОИ-02Т")
ESE_I18N_STRING_ENTRY(ru,   istrET1_DCR_SHORT,        "ЭТ")
ESE_I18N_STRING_ENTRY(ru,   istrET1_DCR_LONG,         "Измеритель метеорологических параметров ЭкоТерма")
ESE_I18N_STRING_ENTRY(ru,   istrEGEM1_DCR_SHORT,      "ГЕО-01")
ESE_I18N_STRING_ENTRY(ru,   istrEGEM1_DCR_LONG,       "Головка изм. геомагнитного поля ГЕО-01")
ESE_I18N_STRING_ENTRY(ru,   istrRAD1_DCR_SHORT,       "РАД-01")
ESE_I18N_STRING_ENTRY(ru,   istrRAD1_DCR_LONG,        "Измеритель активности радона РАД-01")
ESE_I18N_STRING_ENTRY(ru,   istrIRA1_DCR_SHORT,       "ИКИ-01")
ESE_I18N_STRING_ENTRY(ru,   istrIRA1_DCR_LONG,        "Измеритель ИК излучения ИКИ-01")
ESE_I18N_STRING_ENTRY(ru,   istrLD1V_DCR_SHORT,       "ЛД-01-В")
ESE_I18N_STRING_ENTRY(ru,   istrLD1V_DCR_LONG,        "Головка лазерная дозиметрическая ЛД-01-В")
ESE_I18N_STRING_ENTRY(ru,   istrOAA_DCR_SHORT,        "ПИГО")
ESE_I18N_STRING_ENTRY(ru,   istrOAA_DCR_LONG,         "Преобразователь ИГ Октава")
ESE_I18N_STRING_ENTRY(ru,   istrEL3C_DCR_SHORT,       "eL-03-C")
ESE_I18N_STRING_ENTRY(ru,   istrEL3C_DCR_LONG,        "eLight-03-C")
ESE_I18N_STRING_ENTRY(ru,   istrECLG1_DCR_SHORT,      "eCLg-01")
ESE_I18N_STRING_ENTRY(ru,   istrECLG1_DCR_LONG,       "eCoLogger-01")
ESE_I18N_STRING_ENTRY(ru,   istrLUPINX_DCR_SHORT,     "Lupin-X")
ESE_I18N_STRING_ENTRY(ru,   istrLUPINX_DCR_LONG,      "Lupin-X")
// Octava devices description strings
ESE_I18N_STRING_ENTRY(ru,   istrP380E_DCR_SHORT,      "П3-80Е")
ESE_I18N_STRING_ENTRY(ru,   istrP380E_DCR_LONG,       "Измеритель электростатических полей П3-80Е")
ESE_I18N_STRING_ENTRY(ru,   istrP3811_DCR_SHORT,      "П3-81-1")
ESE_I18N_STRING_ENTRY(ru,   istrP3811_DCR_LONG,       "Измеритель магнитной индукции П3-81-1 мТл")
ESE_I18N_STRING_ENTRY(ru,   istrP3812_DCR_SHORT,      "П3-81-2")
ESE_I18N_STRING_ENTRY(ru,   istrP3812_DCR_LONG,       "Измеритель магнитной индукции П3-81-2 мкТл")	
// Tenzor devices description strings
ESE_I18N_STRING_ENTRY(ru,   istrTECOL1_DCR_SHORT,     "ГФ-01")
ESE_I18N_STRING_ENTRY(ru,   istrTECOL1_DCR_LONG,      "Головка фотометрическая ГФ-01")
ESE_I18N_STRING_ENTRY(ru,   istrTBOI1_DCR_SHORT,      "БОИ-01-T")
ESE_I18N_STRING_ENTRY(ru,   istrTBOI1_DCR_LONG,       "Блок отображения информации БОИ-01-T")
ESE_I18N_STRING_ENTRY(ru,   istrTIRA1_DCR_SHORT,      "ИКИ-01-Т")
ESE_I18N_STRING_ENTRY(ru,   istrTIRA1_DCR_LONG,       "Измеритель ИК излучения ИКИ-01-Т")
// Quarta-Rad appliances|hubs description strings
ESE_I18N_STRING_ENTRY(ru,   istrRADEX1_DCR_SHORT,     "RADEX ONE")
ESE_I18N_STRING_ENTRY(ru,   istrRADEX1_DCR_LONG,      "Мини дозиметр Radex One")
ESE_I18N_STRING_ENTRY(ru,   istrMKC1100_DCR_SHORT,    "MKC1100")
ESE_I18N_STRING_ENTRY(ru,   istrMKC1100_DCR_LONG,     "Дозиметр MKC1100")
ESE_I18N_STRING_ENTRY(ru,   istrMR107_DCR_SHORT,      "MR107")
ESE_I18N_STRING_ENTRY(ru,   istrMR107_DCR_LONG,       "Радиометр радона MR107")
ESE_I18N_STRING_ENTRY(ru,   istrAQ_DCR_SHORT,         "Radex AQ")
ESE_I18N_STRING_ENTRY(ru,   istrAQ_DCR_LONG,          "Монитор качества воздуха Radex AQ")
