// core definitions of rpc reflection engine
RPC_REFLECTION_BEGIN
	RPC_DEF_HANDLER0_NORETURN()
	RPC_DEF_HANDLER0(UINT8)
	RPC_DEF_HANDLER0(UINT16)
	RPC_DEF_HANDLER0(UINT32)
	RPC_DEF_HANDLER0(UINT64)
	RPC_DEF_HANDLER0(INT8)
	RPC_DEF_HANDLER0(INT16)
	RPC_DEF_HANDLER0(INT32)
	RPC_DEF_HANDLER0(INT64)
	RPC_DEF_HANDLER0(BOOL)
	RPC_DEF_HANDLER0(DATETIME)
	RPC_DEF_HANDLER0(BYTEARRAY)
	RPC_DEF_HANDLER0(FLOAT)
	RPC_DEF_HANDLER1_NORETURN(	BYTEARRAY)
	RPC_DEF_HANDLER1_NORETURN(	UINT16)
	RPC_DEF_HANDLER1_NORETURN(  FLOAT)
	RPC_DEF_HANDLER1(BOOL, 			DATETIME)
	RPC_DEF_HANDLER1(BYTEARRAY, UINT16)
	RPC_DEF_HANDLER1_NORETURN(	UINT8)
	RPC_DEF_HANDLER1_NORETURN(	UINT32)
	RPC_DEF_HANDLER1_NORETURN(	BOOL)
	RPC_DEF_HANDLER2_NORETURN(	UINT8, 			FLOAT)
	RPC_DEF_HANDLER1(FLOAT,			UINT8)
	RPC_DEF_HANDLER1(UINT16,		BYTEARRAY)
	RPC_DEF_HANDLER2(UINT16,		BYTEARRAY, 	BOOL)
	RPC_DEF_HANDLER1(BYTEARRAY,	BYTEARRAY)
	RPC_DEF_HANDLER2_NORETURN(	UINT8,			BYTEARRAY)
	RPC_DEF_HANDLER1(BYTEARRAY, UINT32)
	RPC_DEF_HANDLER2(BYTEARRAY, UINT32, 		UINT32)	
	RPC_DEF_HANDLER2_NORETURN(	UINT32,			BYTEARRAY)
	RPC_DEF_HANDLER1(BYTEARRAY, UINT8)
RPC_REFLECTION_END

// macro defines housekeeping
#undef RPC_REFLECTION_BEGIN
#undef RPC_DEF_HANDLER0_NORETURN
#undef RPC_DEF_HANDLER1_NORETURN
#undef RPC_DEF_HANDLER2_NORETURN
#undef RPC_DEF_HANDLER3_NORETURN
#undef RPC_DEF_HANDLER4_NORETURN
#undef RPC_DEF_HANDLER5_NORETURN
#undef RPC_DEF_HANDLER6_NORETURN
#undef RPC_DEF_HANDLER0
#undef RPC_DEF_HANDLER1
#undef RPC_DEF_HANDLER2
#undef RPC_DEF_HANDLER3
#undef RPC_DEF_HANDLER4
#undef RPC_DEF_HANDLER5
#undef RPC_DEF_HANDLER6
#undef RPC_REFLECTION_END
